# Generated by Django 5.1.7 on 2025-11-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.candidate'),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='data.occupationalternatetitle'),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='data.skill'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='users.company'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skill_requirements',
            field=models.ManyToManyField(related_name='vacancies', to='core.skillrequirement'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='technologies',
            field=models.ManyToManyField(related_name='vacancies', to='data.technology'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.vacancy'),
        ),
    ]
