# Generated by Django 5.1.7 on 2025-11-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUGGESTED', 'Suggested'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], max_length=255, verbose_name='status'),
        ),
    ]
