# Generated by Django 5.1.7 on 2025-11-08 22:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onet_soc_code', models.CharField(db_index=True, help_text='Unique O*NET-SOC occupation code (e.g. 11-1011.00)', max_length=20, unique=True, verbose_name='O*NET-SOC Code')),
                ('title', models.CharField(db_index=True, help_text='Official occupation title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed occupation description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'ordering': ['onet_soc_code'],
                'indexes': [models.Index(fields=['onet_soc_code'], name='data_occupa_onet_so_0df552_idx'), models.Index(fields=['title'], name='data_occupa_title_c1fcb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(db_index=True, help_text='Unique element identifier (e.g. 2.A.1.a)', max_length=20, unique=True, verbose_name='Element ID')),
                ('element_name', models.CharField(db_index=True, help_text='Skill name (e.g. Reading Comprehension)', max_length=255, verbose_name='Skill name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['element_id'],
                'indexes': [models.Index(fields=['element_id'], name='data_skill_element_0ed2c1_idx'), models.Index(fields=['element_name'], name='data_skill_element_67f90b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(db_index=True, help_text='Unique technology category code', max_length=20, unique=True, verbose_name='Category code')),
                ('commodity_title', models.CharField(db_index=True, help_text='Technology category name', max_length=255, verbose_name='Category title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Technology category',
                'verbose_name_plural': 'Technology categories',
                'ordering': ['commodity_title'],
                'indexes': [models.Index(fields=['commodity_code'], name='data_techno_commodi_cac2fd_idx'), models.Index(fields=['commodity_title'], name='data_techno_commodi_652a2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(db_index=True, help_text='Name of technology or software', max_length=255, verbose_name='Technology name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technologies', to='data.technologycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['example'],
            },
        ),
        migrations.CreateModel(
            name='OccupationAlternateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_title', models.CharField(db_index=True, help_text='Alternative name for the occupation', max_length=255, verbose_name='Alternate title')),
                ('short_title', models.CharField(blank=True, help_text='Abbreviated version of title (e.g. CEO)', max_length=100, null=True, verbose_name='Short title')),
                ('source', models.CharField(blank=True, help_text='Source code for alternate title', max_length=50, null=True, verbose_name='Source')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_titles', to='data.occupation', verbose_name='Occupation')),
            ],
            options={
                'verbose_name': 'Alternate title',
                'verbose_name_plural': 'Alternate titles',
                'ordering': ['occupation', 'alternate_title'],
                'indexes': [models.Index(fields=['alternate_title'], name='data_occupa_alterna_01e3cd_idx'), models.Index(fields=['occupation', 'alternate_title'], name='data_occupa_occupat_47dd70_idx')],
                'unique_together': {('occupation', 'alternate_title')},
            },
        ),
        migrations.CreateModel(
            name='OccupationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_id', models.CharField(choices=[('IM', 'Importance'), ('LV', 'Level')], help_text='Metric type: Importance (IM) or Level (LV)', max_length=2, verbose_name='Scale')),
                ('scale_name', models.CharField(max_length=50, verbose_name='Scale name')),
                ('data_value', models.DecimalField(decimal_places=2, help_text='Metric value (0-10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Value')),
                ('n', models.IntegerField(help_text='Number of observations', verbose_name='Sample size')),
                ('standard_error', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Standard error')),
                ('lower_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Lower CI bound')),
                ('upper_ci_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Upper CI bound')),
                ('recommend_suppress', models.CharField(default='N', max_length=1, verbose_name='Recommend suppress')),
                ('not_relevant', models.CharField(blank=True, max_length=1, null=True, verbose_name='Not relevant')),
                ('date', models.CharField(help_text='Data date (MM/YYYY format)', max_length=10, verbose_name='Date')),
                ('domain_source', models.CharField(max_length=50, verbose_name='Domain source')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_skills', to='data.occupation', verbose_name='Occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_occupations', to='data.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Occupation skill',
                'verbose_name_plural': 'Occupation skills',
                'ordering': ['occupation', 'skill', 'scale_id'],
                'indexes': [models.Index(fields=['occupation', 'skill'], name='data_occupa_occupat_f6f8c8_idx'), models.Index(fields=['scale_id'], name='data_occupa_scale_i_2d2bff_idx'), models.Index(fields=['data_value'], name='data_occupa_data_va_210707_idx')],
                'unique_together': {('occupation', 'skill', 'scale_id')},
            },
        ),
        migrations.CreateModel(
            name='OccupationTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_technology', models.BooleanField(db_index=True, default=False, help_text='Indicates if it is an emerging or high-demand technology', verbose_name='Hot technology')),
                ('in_demand', models.BooleanField(db_index=True, default=False, help_text='Indicates if the technology is currently in high demand', verbose_name='In demand')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_technologies', to='data.occupation', verbose_name='Occupation')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_occupations', to='data.technology', verbose_name='Technology')),
            ],
            options={
                'verbose_name': 'Occupation technology',
                'verbose_name_plural': 'Occupation technologies',
                'ordering': ['occupation', 'technology'],
                'indexes': [models.Index(fields=['occupation', 'technology'], name='data_occupa_occupat_08d20e_idx'), models.Index(fields=['hot_technology'], name='data_occupa_hot_tec_5d23cc_idx'), models.Index(fields=['in_demand'], name='data_occupa_in_dema_52e9b7_idx')],
                'unique_together': {('occupation', 'technology')},
            },
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['example'], name='data_techno_example_256e83_idx'),
        ),
    ]
