# Generated by Django 5.1.7 on 2025-11-08 22:29

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.storage
import utils.enums
import utils.gcp_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.FileField(blank=True, help_text='Candidate CV/Resume file (PDF, DOC, DOCX)', null=True, storage=utils.gcp_storage.GCPStorage(domain=utils.enums.StorageDomain['CANDIDATES'], generate_signed_urls=True, signed_url_expiration=datetime.timedelta(days=1)), upload_to=users.storage.get_candidate_cv_upload_path, verbose_name='CV file')),
                ('hash', models.CharField(blank=True, max_length=355, null=True, verbose_name='hash')),
                ('extraction_result', models.JSONField(blank=True, null=True, verbose_name='extraction result')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('has_mfa', models.BooleanField(default=False, verbose_name='has MFA')),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='MFA secret')),
                ('mfa_verified', models.BooleanField(default=False, verbose_name='MFA verified')),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='MFA verified at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('is_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='verification token')),
                ('verification_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='verification token expires at')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='linkedin url')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='github url')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='portfolio url')),
                ('other_url', models.URLField(blank=True, null=True, verbose_name='other url')),
                ('supervised_data', models.JSONField(blank=True, help_text='Corrected candidate data reviewed and validated by HR person', null=True, verbose_name='supervised data')),
                ('registrated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrated_by_users', to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='candidates', to='core.skillrequirement')),
                ('technologies', models.ManyToManyField(blank=True, related_name='candidates', to='data.technology')),
                ('cv_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='users.cvfile')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
