# Generated by Django 5.1.7 on 2025-11-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='data.skill'),
        ),
    ]
