# Generated by Django 5.2.7 on 2025-11-09 07:16

import datetime
import users.storage
import utils.enums
import utils.gcp_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvfile',
            name='file',
            field=models.FileField(blank=True, help_text='Candidate CV/Resume file (PDF, DOC, DOCX)', max_length=500, null=True, storage=utils.gcp_storage.GCPStorage(domain=utils.enums.StorageDomain['CANDIDATES'], generate_signed_urls=True, signed_url_expiration=datetime.timedelta(days=1)), upload_to=users.storage.get_candidate_cv_upload_path, verbose_name='CV file'),
        ),
    ]
